name: Build and push egov-mdms-services image

on:
  push:
    paths:
      - 'core-services/egov-mdms-service/**'
    branches:
      - build_test

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_PASSWORD_SECRET }}
        password: ${{ secrets.GHCR_USERNAME_SECRET }} 

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./core-services/egov-mdms-service
          file: ./egov-mdms-service
          push: true
          tags: egovernments/egov-mdms-service:v2-${{ env.SHA }}
